[package]
name = "ml"
version = "0.1.0"
edition = "2024"

[dependencies]
ndarray = { version = "0.17.2", features = ["rayon"] } # rayon enables parallel iterators
blas-src = { version = "0.8", features = ["openblas"] }
num-traits = "0.2.19" # or "intel-mkl"

